### ISSUE TITLE
Crashes with Keyboard and setting several options.

### ISSUE THREAD

**Issue by GittyMac** [rockon999/TvSettingsOnFire#1]
First off, you have to start it manually with the MainActivity. Opening keyboard simply crashes. Setting several settings can crash the activity.

**Comment by ewlsh** [comment]
This is built to be integrated with my other project LeanbackLauncher (not launched as a typical application launcher) and secondly did you compile it correctly? You have to link it against an Android jar with hidden APIs enabled. Also, it is only meant to run on API 22 (so ensure that is true). Also, it has to be manually granted numerous permissions (mainly android.permission.WRITE_SECURE_SETTINGS) for self explanatory reasons. The permissions that have to be manually granted can be found in the manifest with ignore tags.
